CREATE TABLE ADD_HISTORY (
    HISTORY_ID NUMBER,
    EXPANDED_NO VARCHAR2(20),
    BEFORE_CAP NUMBER,
    UPDATE_CAP NUMBER,
    INCREASE_DATE DATE,
    CONSTRAINT PK_ADD_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_IS_EXPANDED FOREIGN KEY (EXPANDED_NO) REFERENCES COURSE(IS_EXPANDED)
);
