-- 개설여부에 CHECK 조건 사용해서 0과 1 둘 중 하나만 넣을 수 있게 하기

CREATE TABLE COURSE (
    COURSE_ID VARCHAR2(20),
    COURSE_NO NUMBER(1),
    FACULTY_ID VARCHAR2(20),
    COURSE_NAME VARCHAR2(100),
    COURSE_CREDIT NUMBER(1),
    COURSE_CAP NUMBER(3),
    COURSE_DAY VARCHAR2(10),
    COURSE_TIME VARCHAR2(20),
    COURSE_ROOM VARCHAR2(30),
    COURSE_ENROLLED NUMBER(3),
    IS_EXPANDED VARCHAR2(20),
    IS_OPENED NUMBER(1),
    CONSTRAINT PK_COURSE PRIMARY KEY (COURSE_ID, COURSE_NO),
    CONSTRAINT FK_COURSE_FACULTY FOREIGN KEY (FACULTY_ID) REFERENCES FACULTY(FACULTY_ID)
);

INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C001', 1, 'F001', '데이터베이스프로그래밍', 3, 50, '월,수', '10:30-11:45', '명신관305', 0, 'CA001', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C002', 1, 'F005', '데이터사이언스개론', 3, 130, '월,수', '15:00-16:15', '명신관520', 0, 'CA002', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C002', 2, 'F005', '데이터사이언스개론', 3, 100, '화,목', '10:30-11:45', '명신관702', 0, 'CA003', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C002', 3, 'F005', '데이터사이언스개론', 3, 110, '화,목', '15:00-16:15', '명신관423', 0, 'CA004', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C003', 1, 'F011', '소프트웨어의이해', 3, 50, '화,목', '09:00-10:15', '명신관309', 0, 'CA005', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C003', 2, 'F014', '소프트웨어의이해', 3, 50, '화,목', '15:00-16:15', '명신관305', 0, 'CA006', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C003', 3, 'F013', '소프트웨어의이해', 3, 50, '월,수', '15:00-16:15', '명신관207', 0, 'CA007', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C004', 3, 'F010', '시스템종합설계(캡스톤디자인)', 3, 40, '금', '13:00-16:50', '프라임관304', 0, 'CA008', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C005', 1, 'F016', '시스템프로그래밍', 3, 100, '화,목', '12:00-13:15', '명신관702', 0, 'CA009', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C006', 1, 'F002', '운영체제', 3, 50, '화,목', '15:00-16:15', '명신관413', 0, 'CA010', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C006', 2, 'F002', '운영체제', 3, 50, '화,목', '16:30-17:45', '명신관413', 0, 'CA011', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C006', 3, 'F002', '운영체제', 3, 50, '화,목', '13:30-14:45', '명신관413', 0, 'CA012', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C007', 1, 'F015', '웹시스템설계', 3, 50, '화,목', '10:30-11:45', '명신관413', 0, 'CA013', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C008', 1, 'F011', '인공지능', 3, 50, '월,수', '09:00-10:15', '명신관309', 0, 'CA014', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C009', 1, 'F009', '임베디드시스템', 3, 50, '금', '12:00-15:50', '명신관519', 0, 'CA015', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C010', 1, 'F007', '자료구조', 3, 50, '월,수', '10:30-11:45', '명신관309', 0, 'CA016', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C010', 2, 'F007', '자료구조', 3, 100, '월,수', '13:30-14:45', '명신관605', 0, 'CA017', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C010', 3, 'F016', '자료구조', 3, 70, '화,목', '09:00-10:15', '명신관423', 0, 'CA018', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C011', 1, 'F010', '컴파일러', 3, 50, '월,수', '15:00-16:15', '프라임관204', 0, 'CA019', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C012', 1, 'F015', '컴퓨터구조', 3, 120, '화,목', '09:00-10:15', '명신관520', 0, 'CA020', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C013', 1, 'F003', '컴퓨터네트워크Ⅱ', 3, 50, '화,목', '10:30-11:45', '명신관302', 0, 'CA021', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C014', 1, 'F015', '프로그래밍개론', 3, 40, '화,목', '12:00-13:50', '명신관320', 0, 'CA022', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C014', 2, 'F004', '프로그래밍개론', 3, 70, '화,목', '10:30-11:45', '프라임관203', 0, 'CA023', 0);
INSERT INTO COURSE (COURSE_ID, COURSE_NO, FACULTY_ID, COURSE_NAME, COURSE_CREDIT, COURSE_CAP, COURSE_DAY, COURSE_TIME, COURSE_ROOM, COURSE_ENROLLED, IS_EXPANDED, IS_OPENED) VALUES ('C014', 3, 'F004', '프로그래밍개론', 3, 70, '월,수', '13:30-14:45', '프라임관204', 0, 'CA024', 0);