CREATE TABLE ENROLL_PERIOD (
    PERIOD_ID VARCHAR2(20),
    PERIOD_YEAR NUMBER(4),
    PERIOD_SEM NUMBER(1),
    PERIOD_START DATE,
    PERIOD_END DATE,
    CONSTRAINT PK_ENROLL_PERIOD PRIMARY KEY (PERIOD_ID)
);