CREATE TABLE ENROLL (
    ENROLL_ID VARCHAR2(20),
    STUDENT_ID VARCHAR2(20),
    COURSE_ID VARCHAR2(20),
    COURSE_NO NUMBER(1),
    ENROLL_DATE DATE,
    ENROLL_YEAR NUMBER(4),
    ENROLL_SEM NUMBER(1),
    ENROLL_STAT NUMBER(1),
    ENROLL_CANCEL DATE,
    CONSTRAINT PK_ENROLL PRIMARY KEY (ENROLL_ID),
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY (COURSE_ID, COURSE_NO) REFERENCES COURSE(COURSE_ID, COURSE_NO)
);

INSERT INTO ENROLL (ENROLL_ID, STUDENT_ID, COURSE_ID, COURSE_NO, ENROLL_DATE, ENROLL_YEAR, ENROLL_SEM, ENROLL_STAT, ENROLL_CANCEL) VALUES ('E0001', 'S001', 'C001', 1, TIMESTAMP '2024-02-20 13:58:14', 2024, 1, 1, null);
INSERT INTO ENROLL (ENROLL_ID, STUDENT_ID, COURSE_ID, COURSE_NO, ENROLL_DATE, ENROLL_YEAR, ENROLL_SEM, ENROLL_STAT, ENROLL_CANCEL) VALUES ('E0002', 'S001', 'C010', 1, TIMESTAMP '2021-02-20 13:58:14', 2021, 1, 1, null);
INSERT INTO ENROLL (ENROLL_ID, STUDENT_ID, COURSE_ID, COURSE_NO, ENROLL_DATE, ENROLL_YEAR, ENROLL_SEM, ENROLL_STAT, ENROLL_CANCEL) VALUES ('E0003', 'S001', 'C005', 1, TIMESTAMP '2022-06-01 00:13:56', 2022, 1, 1, null);