CREATE TABLE MAJOR (
    MAJOR_ID VARCHAR2(20),
    MAJOR_NAME VARCHAR2(50),
    CONSTRAINT PK_MAJOR PRIMARY KEY (MAJOR_ID)
);

INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M001', '컴퓨터과학전공');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M002', '데이터사이언스전공');