CREATE TABLE FACULTY (
    FACULTY_ID VARCHAR2(20),
    MAJOR_ID VARCHAR2(20),
    FACULTY_NAME VARCHAR2(20),
    FACULTY_EMAIL VARCHAR2(30),
    FACULTY_POSITION VARCHAR2(20),
    FACULTY_LAB VARCHAR2(30),
    CONSTRAINT PK_FACULTY PRIMARY KEY (FACULTY_ID),
    CONSTRAINT FK_FACULTY FOREIGN KEY (MAJOR_ID) REFERENCES MAJOR(MAJOR_ID)
);

INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F001', 'M001', '심준호', 'jshim@sm.ac.kr', '교수', '새힘관407');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F002', 'M001', '김주균', 'jgkim@sm.ac.kr', '교수', '새힘관412');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F003', 'M001', '최종원', 'choejn@sm.ac.kr', '교수', '새힘관411');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F004', 'M001', '창병모', 'chang@sm.ac.kr', '교수', '새힘관410');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F005', 'M001', '최영우', 'ywchoi@sm.ac.kr', '교수', '새힘관409');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F006', 'M001', '김윤희', 'yulan@sm.ac.kr', '교수', '새힘관402');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F007', 'M001', '유석종', 'sjyu@sm.ac.kr', '교수', '새힘관414');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F008', 'M001', '이기용', 'kiyonglee@sm.ac.kr', '교수', '새힘관406');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F009', 'M001', '김윤진', 'ykim@sm.ac.kr', '교수', '새힘관403');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F010', 'M001', '박영훈', 'yh.park@sm.ac.kr', '교수', '새힘관 101');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F011', 'M001', '채희준', 'heechae@sm.ac.kr', '교수', '새힘관 104');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F012', 'M001', '정영주', 'yjeong@sm.ac.kr', '교수', '새힘관 505');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F013', 'M001', '홍기범', 'kb.hong@sm.ac.kr', '교수', '새힘관 413');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F014', 'M001', '박수현', 'soohyun.park@sm.ac.kr', '교수', '새힘관 405');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F015', 'M001', '박숙영', 'blue@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F016', 'M001', '이현자', 'hyunjalee@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F017', 'M001', '김서영', 'seoyoung.mennelet@gmail.com', '강사', null);
