CREATE TABLE FACULTY (
    FACULTY_ID VARCHAR2(20),
    MAJOR_ID VARCHAR2(20),
    FACULTY_NAME VARCHAR2(20),
    FACULTY_EMAIL VARCHAR2(30),
    FACULTY_POSITION VARCHAR2(20),
    FACULTY_LAB VARCHAR2(30),
    CONSTRAINT PK_FACULTY PRIMARY KEY (FACULTY_ID),
    CONSTRAINT FK_FACULTY FOREIGN KEY (MAJOR_ID) REFERENCES MAJOR(MAJOR_ID)
);

INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F001', 'M001', '심준호', 'jshim@sm.ac.kr', '교수', '새힘관407');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F002', 'M001', '김주균', 'jgkim@sm.ac.kr', '교수', '새힘관412');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F003', 'M001', '최종원', 'choejn@sm.ac.kr', '교수', '새힘관411');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F004', 'M001', '창병모', 'chang@sm.ac.kr', '교수', '새힘관410');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F005', 'M001', '최영우', 'ywchoi@sm.ac.kr', '교수', '새힘관409');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F006', 'M001', '김윤희', 'yulan@sm.ac.kr', '교수', '새힘관402');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F007', 'M001', '유석종', 'sjyu@sm.ac.kr', '교수', '새힘관414');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F008', 'M001', '이기용', 'kiyonglee@sm.ac.kr', '교수', '새힘관406');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F009', 'M001', '김윤진', 'ykim@sm.ac.kr', '교수', '새힘관403');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F010', 'M001', '박영훈', 'yh.park@sm.ac.kr', '교수', '새힘관 101');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F011', 'M001', '채희준', 'heechae@sm.ac.kr', '교수', '새힘관 104');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F012', 'M001', '정영주', 'yjeong@sm.ac.kr', '교수', '새힘관 505');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F013', 'M001', '홍기범', 'kb.hong@sm.ac.kr', '교수', '새힘관 413');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F014', 'M001', '박수현', 'soohyun.park@sm.ac.kr', '교수', '새힘관 405');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F015', 'M001', '박숙영', 'blue@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F016', 'M001', '이현자', 'hyunjalee@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F017', 'M001', '김서영', 'seoyoung.mennelet@gmail.com', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F018', 'M003', '정애령', 'arung18@sm.ac.kr', '교수', '사회관132');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F019', 'M026', '김유경', 'youk@sm.ac.kr', '교수', '진리관321');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F020', 'M020', '임상욱', 'sangsang@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F021', 'M005', '홍태숙', 'hongts@sm.ac.kr', '교수', '프라임관321');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F022', 'M005', '전지혜', 'junjh@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F023', 'M005', '김계선', 'kimgs@sm.ac.kr', '교수', '새힘관243');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F024', 'M005', '박혜정', 'parkhj@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F025', 'M010', '정지혜', 'jungjh@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F026', 'M010', '박서희', 'parksh@sm.ac.kr', '교수', '새힘관512');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F027', 'M030', '최철', 'chlcjf@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F028', 'M010', '양다솔', 'yangdsol@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F029', 'M010', '김소미', 'somimi@sm.ac.kr', '교수', '새힘관212');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F030', 'M010', '윤수지', 'sususu@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F031', 'M010', '이천형', 'chunh@sm.ac.kr', '교수', '순헌관421');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F032', 'M010', '최은', 'chioe@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F033', 'M011', '마정혜', 'majh21@sm.ac.kr', '교수', '프라임관213');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F034', 'M028', '이주은', 'leejue@sm.ac.kr', '교수', '새힘관512');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F035', 'M006', '홍성수', 'hongsu@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F036', 'M003', '김혜영', 'kimhyoung@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F037', 'M013', '황유미', 'hwang@sm.ac.kr', '교수', '새힘관222');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F038', 'M013', '남수경', 'namkung@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F039', 'M022', '임미현', 'immihye@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO40', 'M023', '한희숙', 'hanhs@sm.ac.kr', '교수', '순헌관612');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO41', 'M015', '전경숙', 'junksook@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO42', 'M024', '이혜원', 'leehaewon@sm.ac.kr', '교수', '순헌관311');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO43', 'M016', '민나온', 'minon@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO44', 'M027', '최창익', 'choice@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO45', 'M017', '심지현', 'simjih@sm.ac.kr', '교수', '과학관125');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO46', 'M018', '김효은', 'kimhen@sm.ac.kr', '교수', '과학관612');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO47', 'M019', '김철수', 'kimchuls@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('FO48', 'M020', '고승경', 'kosky@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F049', 'M022', '이희영', 'leehe@sm.ac.kr', '교수', '새힘관111');
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F050', 'M021', '박동곤', 'parkdongk@sm.ac.kr', '강사', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F051', 'M028', '노은초', 'cho@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F052', 'M029', '박철순', 'parkcs@sm.ac.kr', '초빙교수', null);
INSERT INTO FACULTY (FACULTY_ID, MAJOR_ID, FACULTY_NAME, FACULTY_EMAIL, FACULTY_POSITION, FACULTY_LAB) VALUES ('F053', 'M030', '오예림', 'ohohyes@sm.ac.kr', '강사', null);

