CREATE TABLE MAJOR (
    MAJOR_ID VARCHAR2(20),
    MAJOR_NAME VARCHAR2(50),
    CONSTRAINT PK_MAJOR PRIMARY KEY (MAJOR_ID)
);

INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M001', '컴퓨터과학전공');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M002', '데이터사이언스전공');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M003', '기초교양학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M004', '경력개발처');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M005', '프랑스언어문화학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M006', '법학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M007', '중어중문학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M008', '의류학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M009', '영문학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M010', '체육교육과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M011', '환경디자인과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M012', '한국어문학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M013', '생명시스템학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M014', '식품영양학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M015', '일본학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M016', '경제학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M017', '수학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M018', '무용과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M019', '문헌정보학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M020', '융합학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M021', '통계학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M022', '화학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M023', '공예과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M024', '아동복지학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M025', '회화과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M026', '가족자원경영학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M027', '미디어학부');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M028', '독일어문화학과');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M029', '국제협력팀');
INSERT INTO MAJOR (MAJOR_ID, MAJOR_NAME) VALUES ('M030', '행정학과');