-- 증원이 이뤄질때마다 ADD_HISTORY에 정보가 저장되는 트리거
CREATE OR REPLACE TRIGGER INCREASE_CAP_HISTORY
BEFORE UPDATE ON COURSE
FOR EACH ROW
BEGIN
    INSERT INTO ADD_HISTORY(HISTORY_ID, EXPANDED_NO, BEFORE_CAP, UPDATE_CAP, INCREASE_DATE)
    VALUES (HISTORY_ID_SEQ.NEXTVAL, :OLD.IS_EXPANDED, :OLD.COURSE_CAP, :NEW.COURSE_CAP, SYSDATE);
END;
/