create FUNCTION DATE_TO_ENROLL_SEMESTER
RETURN NUMBER
IS
    v_month NUMBER;
BEGIN
    SELECT EXTRACT(MONTH FROM SYSDATE) INTO v_month FROM DUAL;
    IF v_month BETWEEN 2 AND 7 THEN
        RETURN 1;
    ELSE
        RETURN 2;
    END IF;
END;
/